In [ ]:
# numpy apka base banega pandas sikhne k liye.
# mathematical operations k liye bahut jyada empower krta h numpy.

In [2]:
import numpy as np
import pandas as pd

In [16]:
# current working directory
import os
os.getcwd()

'C:\\Users\\anup das'

In [15]:
df=pd.read_csv("p2t.csv")

In [16]:
df

,id,time,orig_time,first_time,mat_time,res_time,balance_time,LTV_time,interest_rate_time,rate_time,...,FICO_orig_time,LTV_orig_time,Interest_Rate_orig_time,state_orig_time,hpi_orig_time,default_time,payoff_time,status_time,lgd_time,recovery_res
0,4,25,-2,25,119,NaN,61031.10,33.911009,10.500,5.90,...,587,81.8,10.5,KY,97.99,0,0,0,NaN,NaN
1,4,26,-2,25,119,NaN,60882.42,34.007232,10.500,5.90,...,587,81.8,10.5,KY,97.99,0,0,0,NaN,NaN
2,4,27,-2,25,119,NaN,60729.80,34.335349,10.500,5.90,...,587,81.8,10.5,KY,97.99,0,0,0,NaN,NaN
3,4,28,-2,25,119,NaN,60576.14,34.672545,10.875,5.90,...,587,81.8,10.5,KY,97.99,0,0,0,NaN,NaN
4,4,29,-2,25,119,NaN,60424.39,34.951639,10.875,5.90,...,587,81.8,10.5,KY,97.99,0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62173,49972,52,25,52,145,NaN,180673.24,103.306966,7.500,5.15,...,708,79.8,7.5,AL,226.29,0,0,0,NaN,NaN
62174,49972,53,25,52,145,NaN,179944.95,95.736862,7.500,5.15,...,708,79.8,7.5,AL,226.29,0,0,0,NaN,NaN
62175,49972,54,25,52,145,NaN,179451.81,91.867079,7.500,5.15,...,708,79.8,7.5,AL,226.29,0,0,0,NaN,NaN
62176,49972,55,25,52,145,NaN,178952.48,91.560581,7.500,5.15,...,708,79.8,7.5,AL,226.29,0,0,0,NaN,NaN
62177,49972,56,25,52,145,NaN,178952.48,90.874242,7.500,5.15,...,708,79.8,7.5,AL,226.29,1,0,1,0.0,178952.48

***Numpy***

**Creating Numpy Array**

In [24]:
my_list=[1,2,3,4]

In [25]:
type(my_list)

list

In [ ]:
# cast a list into Numpy Array

In [27]:
arr=np.array(my_list)

In [28]:
arr

array([1, 2, 3, 4])

In [29]:
df['id']

0            4
1            4
2            4
3            4
4            4
         ...
62173    49972
62174    49972
62175    49972
62176    49972
62177    49972
Name: id, Length: 62178, dtype: int64

In [30]:
arr2=np.array(df['id'])

In [31]:
arr2

array([    4,     4,     4, ..., 49972, 49972, 49972], dtype=int64)

In [32]:
my_list=([1,2,3],[4,5,6],[7,8,9],[32,2,3])

In [33]:
arr5=np.array(my_list)

In [34]:
arr5

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [32,  2,  3]])

In [35]:
arr5.shape

(4, 3)

***Difference b/w list and array***

*Numpy  arrays  support  "vectorized"  operations*

In [39]:
my_list=[50,100]

In [40]:
my_list/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [41]:
arr7=np.array([50,100])

In [42]:
arr7

array([ 50, 100])

In [43]:
arr7/2

array([25., 50.])

In [44]:
a=[1,2,3]
x=np.array(a)
x+3

array([4, 5, 6])

*Ability to broadcast*

In [45]:
arr_ind=np.random.randint(1,100,10)

In [46]:
arr_ind

array([82, 11, 91, 37, 56, 84, 98, 25, 10, 39])

In [47]:
arr_ind[0:3]=50

In [48]:
arr_ind

array([50, 50, 50, 37, 56, 84, 98, 25, 10, 39])

**Built-in methods-(arrange,linspace)**

In [50]:
range(5)

range(0, 5)

In [59]:
arr_10=np.arange(0,11,0.5)

In [60]:
arr_10

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [69]:
arr_11=np.linspace(0,10,30)

In [70]:
arr_11

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [71]:
np.zeros(3)

array([0., 0., 0.])

In [3]:
np.ones(3)

array([1., 1., 1.])

In [4]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# identity matrix m rows(n)=Columns(m).

In [9]:
# creating new column in the dataframe
df["new"]=np.linspace(0,1000,df.shape[0])

In [10]:
df

,id,time,orig_time,first_time,mat_time,res_time,balance_time,LTV_time,interest_rate_time,rate_time,...,LTV_orig_time,Interest_Rate_orig_time,state_orig_time,hpi_orig_time,default_time,payoff_time,status_time,lgd_time,recovery_res,new
0,4,25,-2,25,119,NaN,61031.10,33.911009,10.500,5.90,...,81.8,10.5,KY,97.99,0,0,0,NaN,NaN,0.000000
1,4,26,-2,25,119,NaN,60882.42,34.007232,10.500,5.90,...,81.8,10.5,KY,97.99,0,0,0,NaN,NaN,0.016083
2,4,27,-2,25,119,NaN,60729.80,34.335349,10.500,5.90,...,81.8,10.5,KY,97.99,0,0,0,NaN,NaN,0.032166
3,4,28,-2,25,119,NaN,60576.14,34.672545,10.875,5.90,...,81.8,10.5,KY,97.99,0,0,0,NaN,NaN,0.048249
4,4,29,-2,25,119,NaN,60424.39,34.951639,10.875,5.90,...,81.8,10.5,KY,97.99,0,0,0,NaN,NaN,0.064332
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62173,49972,52,25,52,145,NaN,180673.24,103.306966,7.500,5.15,...,79.8,7.5,AL,226.29,0,0,0,NaN,NaN,999.935668
62174,49972,53,25,52,145,NaN,179944.95,95.736862,7.500,5.15,...,79.8,7.5,AL,226.29,0,0,0,NaN,NaN,999.951751
62175,49972,54,25,52,145,NaN,179451.81,91.867079,7.500,5.15,...,79.8,7.5,AL,226.29,0,0,0,NaN,NaN,999.967834
62176,49972,55,25,52,145,NaN,178952.48,91.560581,7.500,5.15,...,79.8,7.5,AL,226.29,0,0,0,NaN,NaN,999.983917
62177,49972,56,25,52,145,NaN,178952.48,90.874242,7.500,5.15,...,79.8,7.5,AL,226.29,1,0,1,0.0,178952.48,1000.000000

**Creating Random array-rand,randn,randint**

In [12]:
arr_12=np.random.rand(50)
arr_12

array([0.45441607, 0.5296088 , 0.76617429, 0.8096242 , 0.39825524,
       0.74674123, 0.81498161, 0.00833366, 0.01704321, 0.32583268,
       0.41602631, 0.08275356, 0.61059659, 0.02610717, 0.26142748,
       0.18031351, 0.1101976 , 0.08798118, 0.80633883, 0.34146763,
       0.84395993, 0.02413735, 0.80969129, 0.36064187, 0.02838937,
       0.45392607, 0.03406809, 0.51178768, 0.09932193, 0.85063723,
       0.89462004, 0.18430782, 0.28439431, 0.22618851, 0.29823029,
       0.68256314, 0.02773583, 0.19292503, 0.18781094, 0.06225648,
       0.33609611, 0.95658856, 0.42788267, 0.5132288 , 0.94207158,
       0.99065067, 0.37912151, 0.57344053, 0.73290153, 0.9161824 ])

In [13]:
# iss se hm ek matrix bhi bana sakte hn
np.random.rand(5,4)

array([[0.30267618, 0.13623291, 0.42294014, 0.1706682 ],
       [0.27971708, 0.34758388, 0.68671346, 0.85186465],
       [0.23065145, 0.41357815, 0.34235712, 0.02054211],
       [0.88629502, 0.45396143, 0.63345749, 0.51238885],
       [0.9050948 , 0.91711524, 0.36112792, 0.37498538]])

In [14]:
# rand sirf +ve values de rha tha,randn (normal dist.) +ve and -ve values dono dega.
arr_13=np.random.randn(50)
arr_13

array([ 0.37477655, -0.96842615,  1.7076418 , -0.64672209,  0.16307585,
        0.38208273, -0.07216885,  0.89538791, -1.05016451,  0.05025391,
        1.70416112, -1.53954351,  0.23452888,  0.13457564,  0.76014669,
       -0.50349296, -0.56454128, -0.91499944, -0.47802911, -1.56503255,
        0.93463121,  1.09885942, -0.2514347 , -0.01462836, -0.34848718,
        0.36475307, -1.66804797,  0.96002421, -0.62775085,  1.98377991,
        0.47680976, -1.92175203, -0.49616122,  0.77563514,  0.36314565,
        0.56779767,  0.76266329,  0.95966307,  0.05949982, -0.1377018 ,
       -0.58824558,  0.66724545, -0.68711761,  2.83780918,  0.13132883,
       -0.07166572, -1.05314694, -1.45682884,  0.54333217, -0.66546497])

In [18]:
arr_14=np.random.randint(10,50,10)
arr_14

array([30, 44, 32, 43, 18, 27, 25, 31, 43, 42])

***Methods and Operations***

In [6]:
arr_14=np.random.randint(1,500,25)
arr_14

array([ 89, 317, 432, 226, 149, 287, 441, 337, 193, 417,  14, 306, 388,
       448,  76, 442, 235,   4,  90, 220,  16, 289,  73, 284, 454])

In [7]:
matrix_1=arr_14.reshape(5,5)
matrix_1

array([[ 89, 317, 432, 226, 149],
       [287, 441, 337, 193, 417],
       [ 14, 306, 388, 448,  76],
       [442, 235,   4,  90, 220],
       [ 16, 289,  73, 284, 454]])

In [10]:
arr_14.max()

490

In [11]:
arr_14.min()

13

In [12]:
# index locatio of your maximum.
arr_14.argmax()

8

In [13]:
np.exp(arr_14)

array([3.69181433e+075, 3.74645461e+108, 1.39864217e+141, 8.49819210e+178,
       4.42413392e+005, 1.59162664e+091, 9.81390275e+161, 1.10051434e+079,
       6.37229881e+212, 1.31342868e+204, 1.51677688e+187, 3.55767804e+128,
       2.00034922e+196, 8.28132117e+188, 1.13333149e+145, 9.63666567e+052,
       7.17107760e+205, 2.19364928e+199, 1.73927494e+018, 5.18470553e+021,
       1.91409702e+097, 4.79781333e+051, 1.01480039e+033, 2.30190127e+103,
       4.86882283e+084])

In [14]:
np.log(arr_14)

array([5.1590553 , 5.52146092, 5.78382518, 6.02102335, 2.56494936,
       5.34710753, 5.92157842, 5.20400669, 6.19440539, 6.15273269,
       6.06610809, 5.69035945, 6.11368218, 6.07534603, 5.81114099,
       4.80402104, 6.16120732, 6.12905021, 3.73766962, 3.91202301,
       5.41164605, 4.77912349, 4.33073334, 5.47227067, 5.27299956])

In [18]:
np.log(df['LTV_time'])

C:\Anup Dass\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

0        3.523740
1        3.526573
2        3.536175
3        3.545948
4        3.553965
           ...
62173    4.637705
62174    4.561603
62175    4.520343
62176    4.517001
62177    4.509477
Name: LTV_time, Length: 62178, dtype: float64

In [21]:
matrix_1

array([[174, 250, 325, 412,  13],
       [210, 373, 182, 490, 470],
       [431, 296, 452, 435, 334],
       [122, 474, 459,  42,  50],
       [224, 119,  76, 238, 195]])

In [9]:
mat_2=matrix_1.transpose()
mat_2

array([[ 89, 287,  14, 442,  16],
       [317, 441, 306, 235, 289],
       [432, 337, 388,   4,  73],
       [226, 193, 448,  90, 284],
       [149, 417,  76, 220, 454]])

In [22]:
# matrix se array m convert krna h toh.
mat_2.reshape(-1)

array([174, 210, 431, 122, 224, 250, 373, 296, 474, 119, 325, 182, 452,
       459,  76, 412, 490, 435,  42, 238,  13, 470, 334,  50, 195])

In [25]:
dot_product=np.dot(matrix_1,mat_2)
dot_product

array([[368314, 396930, 479456, 306857, 194017],
       [396930, 677353, 653312, 330040, 313529],
       [479456, 653312, 778462, 435324, 334780],
       [306857, 330040, 435324, 454505, 138364],
       [194017, 313529, 334780, 138364, 164782]])

In [26]:
x = [1,2,0]
y = [4,5,6]
np.cross(x,y)

array([12, -6, -3])

In [ ]:
x= np.array([[1,2,3],[4,5,6]])
y= np.array([[4,5,6],[1,2,3]])
np

In [ ]:
# row wise or column wise operations on matrix

In [10]:
mat_2

array([[ 89, 287,  14, 442,  16],
       [317, 441, 306, 235, 289],
       [432, 337, 388,   4,  73],
       [226, 193, 448,  90, 284],
       [149, 417,  76, 220, 454]])

In [11]:
np.sum(mat_2)

6227

In [12]:
# axis=0 matlab row and axis=1 matlab column.
np.sum(mat_2,axis=0)

array([1213, 1675, 1232,  991, 1116])

In [13]:
np.sum(mat_2,axis=1)

array([ 848, 1588, 1234, 1241, 1316])

**Index and Selection**

In [14]:
# Creating sample array
arr_ind = np.random.randint(1,100,10)

In [15]:
arr_ind

array([39, 21, 20, 31, 64, 54, 74, 16, 68, 45])

In [16]:
arr_ind[8]

68

In [17]:
arr_ind[:5]

array([39, 21, 20, 31, 64])

In [ ]:
matrix_1[rows,columns]

In [19]:
matrix_1

array([[ 89, 317, 432, 226, 149],
       [287, 441, 337, 193, 417],
       [ 14, 306, 388, 448,  76],
       [442, 235,   4,  90, 220],
       [ 16, 289,  73, 284, 454]])

In [18]:
matrix_1[2]

array([ 14, 306, 388, 448,  76])

In [20]:
# matrix_1[:2,1:]....................        [lower limit : upper limit]
matrix_1[:2,1:]

array([[317, 432, 226, 149],
       [441, 337, 193, 417]])

In [21]:
matrix_1[matrix_1>50]

array([ 89, 317, 432, 226, 149, 287, 441, 337, 193, 417, 306, 388, 448,
        76, 442, 235,  90, 220, 289,  73, 284, 454])

In [22]:
# single element k liye
matrix_1[2][0]

14

In [3]:
year_1=np.array([[.94,.045,.015],[0.10,0.85,0.05],[0,0,1]])
year_2=np.array([[.95,.047,.013],[0.096,0.03,0.055],[0,0,1]])
year_3=np.array([[.93,.054,.017],[0.094,0.87,0.057],[0,0,1]])

In [4]:
year_1,year_2,year_3

(array([[0.94 , 0.045, 0.015],
        [0.1  , 0.85 , 0.05 ],
        [0.   , 0.   , 1.   ]]),
 array([[0.95 , 0.047, 0.013],
        [0.096, 0.03 , 0.055],
        [0.   , 0.   , 1.   ]]),
 array([[0.93 , 0.054, 0.017],
        [0.094, 0.87 , 0.057],
        [0.   , 0.   , 1.   ]]))

In [5]:
cum_pd_2_yr = np.dot(year_1,year_2)

In [6]:
cum_pd_2_yr

array([[0.89732 , 0.04553 , 0.029695],
       [0.1766  , 0.0302  , 0.09805 ],
       [0.      , 0.      , 1.      ]])

In [7]:
cum_pd_3_yr = np.dot(year_3,cum_pd_2_yr)

In [8]:
cum_pd_3_yr

array([[0.844044  , 0.0439737 , 0.04991105],
       [0.23799008, 0.03055382, 0.14509483],
       [0.        , 0.        , 1.        ]])