In [2]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv("p2t.csv")

In [5]:
df

,id,time,orig_time,first_time,mat_time,res_time,balance_time,LTV_time,interest_rate_time,rate_time,...,FICO_orig_time,LTV_orig_time,Interest_Rate_orig_time,state_orig_time,hpi_orig_time,default_time,payoff_time,status_time,lgd_time,recovery_res
0,4,25,-2,25,119,NaN,61031.10,33.911009,10.500,5.90,...,587,81.8,10.5,KY,97.99,0,0,0,NaN,NaN
1,4,26,-2,25,119,NaN,60882.42,34.007232,10.500,5.90,...,587,81.8,10.5,KY,97.99,0,0,0,NaN,NaN
2,4,27,-2,25,119,NaN,60729.80,34.335349,10.500,5.90,...,587,81.8,10.5,KY,97.99,0,0,0,NaN,NaN
3,4,28,-2,25,119,NaN,60576.14,34.672545,10.875,5.90,...,587,81.8,10.5,KY,97.99,0,0,0,NaN,NaN
4,4,29,-2,25,119,NaN,60424.39,34.951639,10.875,5.90,...,587,81.8,10.5,KY,97.99,0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62173,49972,52,25,52,145,NaN,180673.24,103.306966,7.500,5.15,...,708,79.8,7.5,AL,226.29,0,0,0,NaN,NaN
62174,49972,53,25,52,145,NaN,179944.95,95.736862,7.500,5.15,...,708,79.8,7.5,AL,226.29,0,0,0,NaN,NaN
62175,49972,54,25,52,145,NaN,179451.81,91.867079,7.500,5.15,...,708,79.8,7.5,AL,226.29,0,0,0,NaN,NaN
62176,49972,55,25,52,145,NaN,178952.48,91.560581,7.500,5.15,...,708,79.8,7.5,AL,226.29,0,0,0,NaN,NaN
62177,49972,56,25,52,145,NaN,178952.48,90.874242,7.500,5.15,...,708,79.8,7.5,AL,226.29,1,0,1,0.0,178952.48

In [4]:
type(df['id'])

pandas.core.series.Series

In [ ]:
type(df['id'])

In [5]:
df['id']

0            4
1            4
2            4
3            4
4            4
         ...
62173    49972
62174    49972
62175    49972
62176    49972
62177    49972
Name: id, Length: 62178, dtype: int64

**Series**

In [ ]:
# A series is very similar to a Numpy array (infact it is built on top of the Numpy array object).
# what differentiate the Numpy array from it Series, is that a Series can have axis levels, meaning it can be indexed by a label,instead of just a number.
# It also doesn't need to hold numeric data, it can hold any arbitrary python Object.

In [10]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [ ]:
# using lists heading

In [11]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [14]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
# Numpy arrays

In [15]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [17]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int32

In [ ]:
# Creating Custom Series DS

In [18]:
ser2=pd.Series([6.3,3,5,6.5,6.9])
ser2

0    6.3
1    3.0
2    5.0
3    6.5
4    6.9
dtype: float64

In [21]:
ser1 = pd.Series([12,23,32,43],index = ['USA','Germany','USSR','Japan'])
ser1

USA        12
Germany    23
USSR       32
Japan      43
dtype: int64

In [23]:
dataframe_1=pd.DataFrame(ser1)
dataframe_1

          0
USA      12
Germany  23
USSR     32
Japan    43

In [25]:
ser1+ser1

USA        24
Germany    46
USSR       64
Japan      86
dtype: int64

In [27]:
ser1["USA"]

12

**DataFrame**

In [28]:
# Dataframe as a bunch of Series put together to share the same index

In [29]:
# df although we have our df we still learn to create

In [30]:
df

,id,time,orig_time,first_time,mat_time,res_time,balance_time,LTV_time,interest_rate_time,rate_time,...,FICO_orig_time,LTV_orig_time,Interest_Rate_orig_time,state_orig_time,hpi_orig_time,default_time,payoff_time,status_time,lgd_time,recovery_res
0,4,25,-2,25,119,NaN,61031.10,33.911009,10.500,5.90,...,587,81.8,10.5,KY,97.99,0,0,0,NaN,NaN
1,4,26,-2,25,119,NaN,60882.42,34.007232,10.500,5.90,...,587,81.8,10.5,KY,97.99,0,0,0,NaN,NaN
2,4,27,-2,25,119,NaN,60729.80,34.335349,10.500,5.90,...,587,81.8,10.5,KY,97.99,0,0,0,NaN,NaN
3,4,28,-2,25,119,NaN,60576.14,34.672545,10.875,5.90,...,587,81.8,10.5,KY,97.99,0,0,0,NaN,NaN
4,4,29,-2,25,119,NaN,60424.39,34.951639,10.875,5.90,...,587,81.8,10.5,KY,97.99,0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62173,49972,52,25,52,145,NaN,180673.24,103.306966,7.500,5.15,...,708,79.8,7.5,AL,226.29,0,0,0,NaN,NaN
62174,49972,53,25,52,145,NaN,179944.95,95.736862,7.500,5.15,...,708,79.8,7.5,AL,226.29,0,0,0,NaN,NaN
62175,49972,54,25,52,145,NaN,179451.81,91.867079,7.500,5.15,...,708,79.8,7.5,AL,226.29,0,0,0,NaN,NaN
62176,49972,55,25,52,145,NaN,178952.48,91.560581,7.500,5.15,...,708,79.8,7.5,AL,226.29,0,0,0,NaN,NaN
62177,49972,56,25,52,145,NaN,178952.48,90.874242,7.500,5.15,...,708,79.8,7.5,AL,226.29,1,0,1,0.0,178952.48

**Creating Subset**

In [24]:
df2=df[['id','time','mat_time']][0:9]
df2

   id  time  mat_time
0   4    25       119
1   4    26       119
2   4    27       119
3   4    28       119
4   4    29       119
5   4    30       119
6   4    31       119
7   4    32       119
8   4    33       119

**Creating DF**

In [13]:
df1=pd.DataFrame(np.random.randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [14]:
df1

          W         X         Y         Z
A -0.743060  1.081275  0.678195 -2.280146
B  1.401060 -0.222900 -0.172606 -0.372512
C -0.318748  0.257006  0.955573 -0.895278
D  0.503573  0.478346  0.229320  0.384685
E -0.080544 -0.286261 -0.423842  1.237714

In [13]:
df1[['W','X']]

          W         X
A  1.589425 -0.045772
B -0.208189 -0.862395
C -0.748519 -0.335421
D  0.681246  1.537414
E  1.832120  1.581539

In [7]:
df["times_2"]=df["LTV_time"].apply(lambda x:x*2)
df

,id,time,orig_time,first_time,mat_time,res_time,balance_time,LTV_time,interest_rate_time,rate_time,...,LTV_orig_time,Interest_Rate_orig_time,state_orig_time,hpi_orig_time,default_time,payoff_time,status_time,lgd_time,recovery_res,times_2
0,4,25,-2,25,119,NaN,61031.10,33.911009,10.500,5.90,...,81.8,10.5,KY,97.99,0,0,0,NaN,NaN,67.822017
1,4,26,-2,25,119,NaN,60882.42,34.007232,10.500,5.90,...,81.8,10.5,KY,97.99,0,0,0,NaN,NaN,68.014464
2,4,27,-2,25,119,NaN,60729.80,34.335349,10.500,5.90,...,81.8,10.5,KY,97.99,0,0,0,NaN,NaN,68.670698
3,4,28,-2,25,119,NaN,60576.14,34.672545,10.875,5.90,...,81.8,10.5,KY,97.99,0,0,0,NaN,NaN,69.345090
4,4,29,-2,25,119,NaN,60424.39,34.951639,10.875,5.90,...,81.8,10.5,KY,97.99,0,0,0,NaN,NaN,69.903277
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62173,49972,52,25,52,145,NaN,180673.24,103.306966,7.500,5.15,...,79.8,7.5,AL,226.29,0,0,0,NaN,NaN,206.613933
62174,49972,53,25,52,145,NaN,179944.95,95.736862,7.500,5.15,...,79.8,7.5,AL,226.29,0,0,0,NaN,NaN,191.473724
62175,49972,54,25,52,145,NaN,179451.81,91.867079,7.500,5.15,...,79.8,7.5,AL,226.29,0,0,0,NaN,NaN,183.734158
62176,49972,55,25,52,145,NaN,178952.48,91.560581,7.500,5.15,...,79.8,7.5,AL,226.29,0,0,0,NaN,NaN,183.121162
62177,49972,56,25,52,145,NaN,178952.48,90.874242,7.500,5.15,...,79.8,7.5,AL,226.29,1,0,1,0.0,178952.48,181.748485

**Declaring a list to be converted into column**

In [9]:
new2=np.arange(0,9)

In [10]:
new2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
df2["new_col"]=new2
df2

   id  time  mat_time  new_col
0   4    25       119        0
1   4    26       119        1
2   4    27       119        2
3   4    28       119        3
4   4    29       119        4
5   4    30       119        5
6   4    31       119        6
7   4    32       119        7
8   4    33       119        8

In [26]:
df2.insert(2,"col_nm",new2)
df2

   id  time  col_nm  mat_time  new_col
0   4    25       0       119        0
1   4    26       1       119        1
2   4    27       2       119        2
3   4    28       3       119        3
4   4    29       4       119        4
5   4    30       5       119        5
6   4    31       6       119        6
7   4    32       7       119        7
8   4    33       8       119        8

In [28]:
df2.assign(inter_rate=[0,1,2,3,4,5,6,7,8])

   id  time  col_nm  mat_time  new_col  inter_rate
0   4    25       0       119        0           0
1   4    26       1       119        1           1
2   4    27       2       119        2           2
3   4    28       3       119        3           3
4   4    29       4       119        4           4
5   4    30       5       119        5           5
6   4    31       6       119        6           6
7   4    32       7       119        7           7
8   4    33       8       119        8           8

**Removing Columns**

In [30]:
df2

   id  time  col_nm  mat_time  new_col
0   4    25       0       119        0
1   4    26       1       119        1
2   4    27       2       119        2
3   4    28       3       119        3
4   4    29       4       119        4
5   4    30       5       119        5
6   4    31       6       119        6
7   4    32       7       119        7
8   4    33       8       119        8

In [31]:
df2.drop("col_nm",axis=1,inplace=True) #inplace=True, permanent change k liye krte hn.
df2

   id  time  mat_time  new_col
0   4    25       119        0
1   4    26       119        1
2   4    27       119        2
3   4    28       119        3
4   4    29       119        4
5   4    30       119        5
6   4    31       119        6
7   4    32       119        7
8   4    33       119        8

In [32]:
# agar rows ko remove karna h toh
df2.drop([2,4],axis=0)

   id  time  mat_time  new_col
0   4    25       119        0
1   4    26       119        1
3   4    28       119        3
5   4    30       119        5
6   4    31       119        6
7   4    32       119        7
8   4    33       119        8